// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crqxdydidjnrhhiihbtd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNycXhkeWRpZGpucmhoaWloYnRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNTI1OTcsImV4cCI6MjA1NjcyODU5N30.z9GNBI020Ur84JYrw6nnAFo7RbeP63l9_bgUmPUBNmk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);